### PR TITLE
Allow for async execution of aggregation writes

### PR DESCRIPTION
**Pull request by meatballhat**

### CODE REVIEW

**Comment by meatballhat** [comment]
This is working as expected now :tada:

**Comment by joshk** [comment]
this looks very cool, one question, if the loop adds a bunch of ids to be aggregated, how does it know not to create a duplicate job of the same ids as they might not be processed yet?

**Comment by meatballhat** [comment]
@joshk That's definitely a potential source of leakage.  If the aggregator process dies for some reason, or otherwise isn't consuming work, then lots of duplicate Sidekiq jobs will pile up.  I've tested this scenario in staging already, and the net result is still desirable/correct, but it certainly has the potential to pile up a lot of unnecessary work.  I think that in the worst case, we can purge the Sidekiq queue and let the `aggregate` process start over, or even disable async aggregation.

**Comment by joshk** [comment]
@meatballhat if we schedule an aggregate job for a log id, then schedule it again, will the second job wipe the content of the job?

**Comment by joshk** [comment]
should we consider adding an state check to see if the job has been queued for aggregation?

**Comment by meatballhat** [comment]
@joshk the current version aims to avoid remaining race/duplicate conditions by setting uniqueness on aggregation jobs & creating each with a single log id rather than an array :+1:

**Comment by meatballhat** [comment]
:tada: this is working correctly in staging

**Comment by henrikhodne** [comment]
:sparkles: This looks correct to me :+1: :sparkles:

**Pull request merged**
