### PR TITLE
Planning partman + sqitch

### PR DESCRIPTION
**Pull request by meatballhat**
Targeting #96 

## partman on log_parts

This change seeks to introduce the use of [pg_partman](https://github.com/keithf4/pg_partman) and to configure it to partition the `log_parts` table and drop partitions past a certain age for purposes of keeping the database size under control.  The selection of pg_partman was based mostly on existing support for it by Heroku, as well as feedback provided by Heroku support while working through tickets involving the travis-logs database.

## sqitch

Included in this change is the introduction of [sqitch](http://sqitch.org) ([repo](https://github.com/theory/sqitch)), a database change management tool that's been used on other projects at Travis CI including [cloud-brain](https://github.com/travis-ci/cloud-brain) and [job-board](https://github.com/travis-ci/job-board).

My reasoning here is that with the recent change to how other applications access travis-logs data to strictly go through the travis-logs HTTP API, that the travis-logs application does not and _should not_ have a relationship with [travis-migrations](https://github.com/travis-ci/travis-migrations).

I realize that with such a change comes the need for considering how an application using a database that is managed outside of travis-migrations should be integrated with Travis Enterprise, which I'd very much like to discuss (not here, probably)!

### CODE REVIEW

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Is the idea to continue using `travis-migrations` for local dev and enterprise?

If we change our prod setup, that also means updating travis-migrations docs.

**Comment by meatballhat** [comment]
@igorwwwwwwwwwwwwwwwwwwww The idea is to get away from travis-migrations and instead use sqitch for logs.  This means that the relationship with travis-migrations, logs, and Travis Enterprise will change, although this is going to be the case in the near future anyway given job-board's status.  I've requested @bnferguson's review here and I'm discussing with the enterprise folks on how best to integrate.

**Comment by bnferguson** [comment]
:wave: Hallooooooo!

First thing: a more fleshed out PR description here would be huge. I'm not super familiar with partman or sqitch or how they relate to the MRI PR (HUGE fan of the MRI change though!). Would help me catch up on what I'm being asked to review quickly (and more importantly, help me later on when I forget and am doing release notes).

But in general, very curious about this! Is there a discussion I can follow around why sqitch that we've had in other projects?

With any changes to migrations, my concerns is more around upgrades than new customers. We've had migration breaks even recently around this (https://github.com/travis-pro/team-teal/issues/1811 & https://github.com/travis-ci/travis-migrations/pull/46, actually looks like this may not have happened with sqitch since it doesn't do numbering, which is cool). But generally the situation with Enterprise is, the db maybe be in any number of states. When we upgrade a customer, we don't know what version they are coming from. On the upside, I can force customers to migrate using the methods we use now up to where 2.1 is at (or 2.2 depending when this change comes in) but we'll need to make sure whatever we move to can handle that state. So we'd need to change any change over migrations to use this new method and have a way to know it's happened. Right now migrations run every time we start or stop the db so any checks of this sort need to be pretty low cost (lol unlike what I did here to solve the previous issue in a pinch that was then reverted: https://github.com/travis-pro/travis-enterprise/pull/168/files ) 

Another thing to note is that in Enterprise the logs db is the same db as the travis one (but may not always be - especially in customers using High Availability). Will this be an issue with sqitch? Having two migration mechanics working in the same db does give me some level of pause. Especially when one is breaking with convention (at least in Ruby projects). Understanding what the upsides and downsides of switching would be good for me.

Finally, with all the work you've been doing with the logs API, do the other projects still access the logs db at all, or do they only go through the API? Reason I'm curious is it could be really nice to get those logs migrations back into the project for sure. Does feel better than it being spread everywhere if they're not needed. 

Finally, thanks so much for thinking of Enterprise! Really really helps us ship things faster! :heart:

**Comment by meatballhat** [comment]
Hi, @bnferguson!

> First thing: a more fleshed out PR description here would be huge. I'm not super familiar with partman or sqitch or how they relate to the MRI PR (HUGE fan of the MRI change though!). Would help me catch up on what I'm being asked to review quickly (and more importantly, help me later on when I forget and am doing release notes).

Yep!  I've filled in more details 👍

> But in general, very curious about this! Is there a discussion I can follow around why sqitch that we've had in other projects?

It's ancient history at this point.  I'd like to have a fresh conversation with those present and affected today.

> With any changes to migrations, my concerns is more around upgrades than new customers. We've had migration breaks even recently around this (travis-pro/team-teal#1811 & travis-ci/travis-migrations#46, actually looks like this may not have happened with sqitch since it doesn't do numbering, which is cool). But generally the situation with Enterprise is, the db maybe be in any number of states. When we upgrade a customer, we don't know what version they are coming from. On the upside, I can force customers to migrate using the methods we use now up to where 2.1 is at (or 2.2 depending when this change comes in) but we'll need to make sure whatever we move to can handle that state. So we'd need to change any change over migrations to use this new method and have a way to know it's happened. Right now migrations run every time we start or stop the db so any checks of this sort need to be pretty low cost (lol unlike what I did here to solve the previous issue in a pinch that was then reverted: https://github.com/travis-pro/travis-enterprise/pull/168/files )

Yep, understood 😺 👍 

> Another thing to note is that in Enterprise the logs db is the same db as the travis one (but may not always be - especially in customers using High Availability). Will this be an issue with sqitch? Having two migration mechanics working in the same db does give me some level of pause. Especially when one is breaking with convention (at least in Ruby projects). Understanding what the upsides and downsides of switching would be good for me.

I do not foresee any issues with this, as hybrid change management has been in place for over a year on job-board, which has its own schema on the primary (shared) database in production.

> Finally, with all the work you've been doing with the logs API, do the other projects still access the logs db at all, or do they only go through the API? Reason I'm curious is it could be really nice to get those logs migrations back into the project for sure. Does feel better than it being spread everywhere if they're not needed.

The other projects no longer use the logs database for reads or writes, although there is currently still a dependency on access to the read-only logs database follower for purposes of building the legacy ActiveRecord models at runtime.  I'm in the process of removing this dependency and removing remaining database access logs-related code from these applications.

On a related note, I believe we can and should start with a structure dump as first "migration" as is the case with the sqitch migrations in this PR.  For existing Enterprise customers, we should be able to safely skip over all of the sqitch migrations defined here by running a one-time `sqitch deploy --to-change partman --log-only`, *OR* by simply ignoring the existence of these sqitch migrations until we have to care.  If, however, you think we should consider including a pg_partman setup in Enterprise, then I'm happy to talk through what that would require.

**Comment by bnferguson** [comment]
> I received confirmation from @bnferguson in a separate conversation that this is OK from an Enterprise perspective, given we will not likely have to migrate Enterprise customers onto a partman-enabled setup.

Sorry for the lack of weigh in here, had intended on doing it before the Easter break but some Enterprise emergencies occupied me. But yup! This is good. Biggest thing is going to be testing upgrade paths from 2.1/2.0 and new setups for Enterprise. Partman _shouldn't_ come into play for any customers anytime soon but I also wouldn't remove the possibility considering the scale of a few of our customers. Even still, I think it's far out and we can formulate what that looks like then. :+1:

**Comment by bnferguson** [comment]
Also didn't get to respond to your earlier responses, which are excellent! (Enterprise release and 
onboarding had me pretty out of the loop the last couple weeks) 

Thank you for taking the time to do that! Makes a much clearer picture for me!

**Pull request merged**
