### PR TITLE
Feature/file sotrage provider

### PR DESCRIPTION
**Pull request by lksv**
It adds feature to store logs on file system. It should be useful in enterprise.

### CODE REVIEW

**Comment by joshk** [comment]
Thanks for the PR, but we are unable to review it until your custom license is removed.

**Comment by lksv** [comment]
I cannot remove custom license for now. My contract do not allow me to do yourself. But I will ask for it. ...unfortunately, it could take some time.

**Comment by joshk** [comment]
I'm sorry, but as you are not able to change the license, I will need to close this PR. 

Thanks for taking the time.

**Comment by lksv** [comment]
Finally I am able to push this (and several other) pull requests without custom licence ...and without violation of my contract...

I squash the branch and remove custom licence commit. Unfortunately I cannot reopen this pull request. Should I open new?

**Pull request closed without merging**
