### PR TITLE
Change "clear log content" API endpoint to "set log content"

### PR DESCRIPTION
**Pull request by henrikhodne**
Clearing a log can be implemented by setting the log to the empty string. This API endpoint is more versatile, though, and can be used for things like writing an error to the logs.

The new endpoint also takes the job ID instead of the log ID, since the log ID is an internal implementation detail that shouldn't really leak outside of the logs app.

### CODE REVIEW

**Comment by svenfuchs** [comment]
@henrikhodne super! :+1: 

If you'd create the log if missing, or added POST to `/logs` then that would cover all cases for both hub and gatekeeper :)

**Comment by henrikhodne** [comment]
> If you'd create the log if missing, or added POST to /logs then that would cover all cases for both hub and gatekeeper :)

Good point, I added that so now `PUT /logs/:id` will create the log if it doesn't already exist.

**Comment by solarce** [comment]
I'm not familiar with the codebase but your changes seem to line up with what you want the API to support, so I'd give it a +1 but you may want another +1 from Dan or Sven before merging.

**Comment by meatballhat** [comment]
:sheep: :it: lovely!

**Comment by svenfuchs** [comment]
@henrikhodne LGTM

:heart: :heart: :heart:

**Comment by svenfuchs** [comment]
@henrikhodne btw what happens when the log has not been aggregated, yet. I.e. when there are still parts waiting?

**Comment by henrikhodne** [comment]
@svenfuchs It deletes all log parts, so those will be discarded.

I guess there's a potential race condition here where the aggregator is in the middle of aggregating, and we set the log content after the aggregator has aggregated all the log parts, but before it sets the log content. We can probably work around that with some transaction magic, but my gut feeling is that the aggregation is so short-lived and doesn't normally happen when this API would be called (which I believe is before a log is started or during a restart, and aggregation will happen a while after the job is finished).

**Comment by henrikhodne** [comment]
This works on staging. No pusher event is sent out, so there's no live update, meaning a refresh is needed to see the update, but I think in the case of a restart the web client clears the local logs itself.

**Comment by henrikhodne** [comment]
@svenfuchs This is in prod now, so feel free to start implementing things using this.

**Pull request merged**
